# Generated by Django 6.1.1 on 2026-09-27 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Tên khách hàng')),
                ('phone', models.CharField(max_length=20, verbose_name='Số điện thoại')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Khách hàng',
                'verbose_name_plural': 'Danh sách Khách hàng',
            },
        ),
        migrations.CreateModel(
            name='PhoneProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên mẫu điện thoại')),
                ('brand', models.CharField(max_length=100, verbose_name='Thương hiệu')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='Mã SKU / IMEI')),
                ('import_price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Giá nhập (VNĐ)')),
                ('selling_price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Giá bán (VNĐ)')),
                ('stock_quantity', models.IntegerField(default=0, verbose_name='Số lượng tồn kho')),
                ('min_warning_limit', models.IntegerField(default=3, verbose_name='Ngưỡng báo động tồn kho')),
            ],
            options={
                'verbose_name': 'Sản phẩm Điện thoại',
                'verbose_name_plural': 'Kho Điện thoại',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Số lượng mua')),
                ('total_price', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Tổng tiền (VNĐ)')),
                ('status', models.CharField(choices=[('PENDING', 'Chờ xử lý'), ('COMPLETED', 'Đã hoàn thành'), ('CANCELLED', 'Đã hủy')], default='COMPLETED', max_length=20, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo đơn')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phone_erp.customer', verbose_name='Khách hàng')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phone_erp.phoneproduct', verbose_name='Sản phẩm điện thoại')),
            ],
            options={
                'verbose_name': 'Đơn hàng',
                'verbose_name_plural': 'Danh sách Đơn hàng',
            },
        ),
    ]
