# Generated by Django 6.1.1 on 2026-09-27 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_erp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=12, verbose_name='Tổng tiền (VNĐ)'),
        ),
    ]
